### ISSUE TITLE
Crash when using Swift standard libraries

### ISSUE THREAD

**Issue by dm-z** [fulldecent/swift5-module-template#38]
I've found an interesting crash, and I'm not sure what would be an ideal solution to fix it.

So steps to reproduce:
1) Generate a project from template
2) Add function to YourProjectName.swift
  func crushFunc() {
    print("Let's crash!")
  }
3) Compile the project for target "iOS Example" or "YouProjectNameTests", you don't even need to call a function, it will crash on launch

To fix this, I had to turn on build setting "Always Embed Swift Standard Libraries" -> YES for both targets (Example and Tests), otherwise it will crash on launch. But this fix will generate warnings if user wants to add Pod Dependencies to the project (Debug + Release for Example and Test targets - 4 combined warning when installing cocoapods):

[!] The `iOS Example [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-iOS Example/Pods-iOS Example.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by fulldecent** [comment]
That you for reporting!

Redockulous problems like this are exactly why I created this project. So now we can go to the jury and say EXACTLY which REPRODUCIBLE steps we did to get into this hole. And then we can learn which step was wrong.

**Comment by fulldecent** [comment]
This appears to be fixed in the latest version.

Here is a complete test cast working with those steps.

https://youtu.be/RKXocrL22hc
