### ISSUE TITLE
No such Module $ModuleName in ContentView.swift (Xcode 12.4)

### ISSUE THREAD

**Issue by fritzfr** [fulldecent/swift5-module-template#48]
Hey,
I wanted to try this out with Xcode 12.4, it seems that it can't find the module.
Any ideas?

**Comment by fritzfr** [comment]
I did manage to successfully accomplish the wanted folder structure by following the recipe manually (https://github.com/fulldecent/swift5-module-template/blob/master/Recipe.md).

**Comment by fulldecent** [comment]
Thank you for sharing. Could you please send the diff of what you produced when doing it manually versus what we released?

**Comment by fulldecent** [comment]
Thank you, the Recipe and module is reprocessed in 2e6ac90. Should all be good now. Please reopen issue if not the case.
