### ISSUE TITLE
Unable to Drag and drop 'xxProjectxNamexx' in to iOS Example.

### ISSUE THREAD

**Issue by johannfza** [fulldecent/swift5-module-template#49]
At Step: VI. Make your iOS Example application depend on your module

I am unable to drag and drop 'xxProjectxNamexx' into Opened 'iOS Example' as a separate package. When I do so it appears with int the iOS Example Project and not as a separate package 

![Screenshot 2021-02-26 at 9 16 46 AM](https://user-images.githubusercontent.com/39438004/109240919-5a528000-7813-11eb-97e6-3ef56b44b8a2.png)

I am trying to create a UIKit Version of the template.

**Comment by fulldecent** [comment]
Thank you for reporting.

Has anyone else seen this too?

**Comment by fulldecent** [comment]
Thank you for the issue. I have confirmed this is tricky to drag and drop that folder there.

The process is detailed here illustrating how to successfully perform the drag drop.

https://youtu.be/ksYXtNn8lhE?t=7m11s
