### ISSUE TITLE
Support for Non-ASCII characters

### ISSUE THREAD

**Issue by nicolas-miari** [fulldecent/swift5-module-template#52]
The `./configure` script works great, but I had to change the author name from the usual "Nicol**á**s Miari" to "Nicol**a**s Miari" (no diactritics) to get it to work, otherwise it would fail with:

```
Traceback (most recent call last):
	8: from ./configure:107:in `<main>'
	7: from ./configure:13:in `replace_variables_in_files'
	6: from ./configure:13:in `glob'
	5: from ./configure:17:in `block in replace_variables_in_files'
	4: from ./configure:17:in `open'
	3: from ./configure:19:in `block (2 levels) in replace_variables_in_files'
	2: from ./configure:19:in `each'
	1: from ./configure:20:in `block (3 levels) in replace_variables_in_files'
./configure:20:in `gsub!': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

I guess I can go back to the generate files and fix it, but it would be nice to have.

**Comment by fulldecent** [comment]
Thank you for sharing this. Could you please try again with the new version published now and share any other tips you have with using diactritics on the latest versions of Xcode?

**Comment by fulldecent** [comment]
Closing for now, please reopen if you see this issue still in the new versions
